#!/usr/bin/env bash
# build: provision the VM and bake the framework source.
#
# Round A scope:
#   1. Validate cwd is a Mosaic project.
#   2. Render the Lima template + start the VM (via render-lima.sh).
#   3. Clone framework source into both ./moodle (host) and /srv/moodle
#      (VM) (via bake.sh).
#
# Round B will add: clone plugins into ./moodle/<dest>; install systemd
# oneshot for per-plugin bind-mounts; mixins.
# Round C will add: generate config.php; admin/cli/install.php; phpunit-init.

set -euo pipefail
. "$(dirname "$0")/lib.sh"

require_project
HOME_DIR=$(mosaic_home)
PROJECT_DIR=$(pwd)
VM_NAME=$(project_vm_name)

FRAMEWORK=$(project_yaml_get framework)
VERSION=$(project_yaml_get version)

info "==> mosaic build"
say  "    project:   $(basename "$PROJECT_DIR")"
say  "    framework: $FRAMEWORK $VERSION"
say  "    vm:        $VM_NAME"
echo

# Step 1: VM up. Idempotent — render-lima.sh's `limactl start` is a
# no-op if the VM already exists and is healthy.
"$HOME_DIR/scripts/render-lima.sh"
echo

# Step 2: framework source + plugin clones on host. Destructive —
# bake.sh nukes /srv/<framework> and ./<framework> before re-cloning.
# Round C+ will gate this on the plugin-state safety check; for now
# every build is a clean slate.
"$HOME_DIR/scripts/bake.sh"
echo

# Step 3: write the plugin-context file. apply-plugins (running in
# the VM) sources this for profile-derived values it can't resolve
# itself — currently just `plugins_root`. Resolving on the host means
# `extends`-aware lookups happen here (lib.sh's profile_get walks the
# inheritance chain) rather than being re-implemented in-VM.
#
# Keeping this even when there are no plugins, so apply-plugins can
# safely run on every boot without conditional plumbing.
mkdir -p .devenv
PLUGINS_ROOT=$(project_plugins_root "$FRAMEWORK" "$VERSION")
{
    echo "# Generated by mosaic build at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Sourced by apply-plugins inside the VM."
    echo "PLUGINS_ROOT=$PLUGINS_ROOT"
} > .devenv/plugin-context

# Step 4: trigger apply-plugins inside the VM. Restart, not start, so
# this works on rebuild — systemctl start on an already-active oneshot
# is a no-op. Restart re-runs the unit with the new mosaic.yaml
# plugin set.
info "==> Applying plugin bind-mounts in VM"
"$HOME_DIR/scripts/in-vm" "$VM_NAME" sudo systemctl restart apply-plugins.service
echo

ok "Round B build complete"
echo
info "Next:"
say  "  mosaic shell        # poke around inside the VM (cd /srv/$FRAMEWORK)"
say  "  mosaic plugins      # list plugin entries from mosaic.yaml"
say  "  mosaic nuke         # destroy the VM (project files survive)"
echo
say  "  Round C (after): config.php, framework install, phpunit-init."
