#!/usr/bin/env bash
# build: provision the VM, bake source, install Moodle, light up
# nginx + php-fpm + db so the user can browse to it on completion.
#
# Steps (Moodle/Workplace/Totara — bake mode):
#   1. Render the Lima template + start the VM (render-lima.sh).
#   2. Clone framework source into ./<framework> (host) and
#      /srv/<framework> (VM); clone plugins into host (bake.sh).
#   3. Write .devenv/plugin-context (host-resolved profile values).
#   4. Trigger apply-plugins.service in the VM (per-plugin bind-mounts).
#   5. Render .devenv/{nginx.conf, php.ini, services-compose.yaml}
#      (render-services.sh). Symlinks are already in place from the
#      Lima provision step, so nginx and php-fpm pick the new files
#      up on next start.
#   6. Start podman compose services (db + mailpit).
#   7. Run admin/cli/install.php; move config.php to host (install-moodle.sh).
#   8. Run admin/cli/upgrade.php so plugin schemas land (upgrade-moodle.sh).
#   9. Start nginx + php-fpm.
#
# At the end the user can `curl http://<wwwroot>:<web_port>/` and see
# Moodle. Login as admin/Password1!.

set -euo pipefail
. "$(dirname "$0")/lib.sh"

require_project
HOME_DIR=$(mosaic_home)
PROJECT_DIR=$(pwd)
VM_NAME=$(project_vm_name)

FRAMEWORK=$(project_yaml_get framework)
VERSION=$(project_yaml_get version)
PHP_VERSION=$(project_yaml_get php.version)
WEB_PORT=$(project_yaml_get ports.web)
WWWROOT=$(project_yaml_get_or wwwroot localhost)

info "==> mosaic build"
say  "    project:   $(basename "$PROJECT_DIR")"
say  "    framework: $FRAMEWORK $VERSION"
say  "    vm:        $VM_NAME"
echo

# Step 1: VM up. Idempotent — render-lima.sh's `limactl start` is a
# no-op if the VM already exists and is healthy.
"$HOME_DIR/scripts/render-lima.sh"
echo

# Step 2: framework source + plugin clones on host. Destructive —
# bake.sh nukes /srv/<framework> and ./<framework> before re-cloning.
# Round C+ will gate this on the plugin-state safety check; for now
# every build is a clean slate.
"$HOME_DIR/scripts/bake.sh"
echo

# Step 3: write the plugin-context file. apply-plugins (running in
# the VM) sources this for profile-derived values it can't resolve
# itself — currently just `plugins_root`. Resolving on the host means
# `extends`-aware lookups happen here (lib.sh's profile_get walks the
# inheritance chain) rather than being re-implemented in-VM.
mkdir -p .devenv
PLUGINS_ROOT=$(project_plugins_root "$FRAMEWORK" "$VERSION")
{
    echo "# Generated by mosaic build at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Sourced by apply-plugins inside the VM."
    echo "PLUGINS_ROOT=$PLUGINS_ROOT"
} > .devenv/plugin-context

# Step 4: trigger apply-plugins inside the VM. Restart, not start, so
# this works on rebuild — systemctl start on an already-active oneshot
# is a no-op. Restart re-runs the unit with the new mosaic.yaml
# plugin set.
info "==> Applying plugin bind-mounts in VM"
"$HOME_DIR/scripts/in-vm" "$VM_NAME" sudo systemctl restart apply-plugins.service
echo

# Step 5: render service configs (nginx vhost, php.ini, podman compose).
"$HOME_DIR/scripts/render-services.sh"
echo

# Step 6: start podman compose services (db, mailpit). Up-d is
# idempotent: re-runs after `mosaic build` reuse the existing
# containers (and the named volume preserves DB data, which gets
# wiped by install.php in step 7 anyway).
info "==> Starting podman services (db, mailpit)"
"$HOME_DIR/scripts/in-vm" "$VM_NAME" \
    podman compose -f /srv/project/.devenv/services-compose.yaml up -d
# install-moodle.sh has its own readiness loop on the db container,
# so no sleep here.
echo

# Step 7: install Moodle (creates DB schema + admin user + config.php).
"$HOME_DIR/scripts/install-moodle.sh"
echo

# Step 7b: patch config.php with phpunit_dataroot + phpunit_prefix so
# `mosaic init-phpunit` works without a re-edit. Cheap and idempotent;
# always-on rather than gated on the phpunit capability because the
# two extra lines in config.php do nothing if phpunit isn't used.
info "==> Patching config.php with phpunit settings"
"$HOME_DIR/scripts/in-vm" "$VM_NAME" \
    sudo /srv/mosaic/scripts/configure-phpunit "/srv/$FRAMEWORK/config.php"
echo

# Step 8: install plugin schemas via Moodle's standard upgrade path.
# install.php only handles core; plugin tables get created here.
if [[ $(project_plugin_count) -gt 0 ]]; then
    "$HOME_DIR/scripts/upgrade-moodle.sh"
    echo
fi

# Step 9: start nginx + php-fpm. The Lima provision step already
# enabled them, but didn't start them at first boot (no config.php
# existed). Start now that everything's wired up.
info "==> Starting nginx + php-fpm"
"$HOME_DIR/scripts/in-vm" "$VM_NAME" \
    sudo systemctl start "php${PHP_VERSION}-fpm" nginx
echo

ok "Round C build complete — Moodle is live"
echo
info "Open it:"
say  "  http://${WWWROOT}:${WEB_PORT}/"
say  "  admin / Password1!"
echo
info "Next:"
say  "  mosaic status        # one-screen summary"
say  "  mosaic init-phpunit  # set up the phpunit test database (capability-gated)"
say  "  mosaic shell         # drop into the VM at /srv/project"
say  "  mosaic down          # stop services without losing state"
