#!/usr/bin/env bash
# build: provision the VM, fetch source, install the framework, light
# up nginx + php-fpm + db so the user can browse to it on completion.
#
# Dispatches on the framework profile's `mode`:
#   bake  → Moodle/Workplace/Totara: bake source into /srv/<framework>,
#           clone plugins on host + bind-mount into VM, install.php,
#           upgrade.php for plugin schemas.
#   mount → Laravel: clone the whole project to host, bind-mount it
#           into VM, composer install + npm install + key:generate +
#           migrate.
#
# At the end the user can `curl http://<wwwroot>:<web_port>/` and see
# the framework. Moodle: log in as admin/Password1!. Laravel: see the
# default welcome (or whatever the project ships).

set -euo pipefail
. "$(dirname "$0")/lib.sh"

require_project
HOME_DIR=$(mosaic_home)
PROJECT_DIR=$(pwd)
VM_NAME=$(project_vm_name)

FRAMEWORK=$(project_yaml_get framework)
VERSION=$(project_yaml_get version)
PHP_VERSION=$(project_yaml_get php.version)
WEB_PORT=$(project_yaml_get ports.web)
WWWROOT=$(project_yaml_get_or wwwroot localhost)
MODE=$(profile_get "$FRAMEWORK" "$VERSION" 'mode')
[[ -n $MODE ]] || die "framework profile has no 'mode' field"

info "==> mosaic build"
say  "    project:   $(basename "$PROJECT_DIR")"
say  "    framework: $FRAMEWORK $VERSION"
say  "    mode:      $MODE"
say  "    vm:        $VM_NAME"
echo

# --- common: VM up --------------------------------------------------------
# Idempotent — render-lima.sh's `limactl start` is a no-op if the VM
# already exists and is healthy.
"$HOME_DIR/scripts/render-lima.sh"
echo

if [[ $MODE == "bake" ]]; then
    # --- bake-specific: fetch framework + plugins ------------------------
    # Destructive — bake.sh nukes /srv/<framework> and ./<framework>
    # before re-cloning. The plugin-state safety check (Round C+) is
    # the user-facing guardrail; for now every build is a clean slate.
    "$HOME_DIR/scripts/bake.sh"
    echo

    # plugin-context: host-resolved profile values for apply-graft
    # (running in the VM, sourced via virtiofs).
    mkdir -p .devenv
    PLUGINS_ROOT=$(project_plugins_root "$FRAMEWORK" "$VERSION")
    {
        echo "# Generated by mosaic build at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "# Sourced by apply-graft inside the VM."
        echo "PLUGINS_ROOT=$PLUGINS_ROOT"
    } > .devenv/plugin-context

    info "==> Grafting plugins + project files in VM"
    "$HOME_DIR/scripts/in-vm" "$VM_NAME" sudo systemctl restart apply-graft.service
    echo

elif [[ $MODE == "mount" ]]; then
    # mount mode does its project clone + dep install AFTER services
    # are up (composer/npm don't need the db, but install-laravel.sh
    # also runs `php artisan migrate` which does). Defer to step
    # below, after `podman compose up`.
    :
else
    die "unknown mode: $MODE"
fi

# --- common: render service configs --------------------------------------
"$HOME_DIR/scripts/render-services.sh"
echo

# --- common: podman services (db + mailpit) ------------------------------
info "==> Starting podman services (db, mailpit)"
"$HOME_DIR/scripts/in-vm" "$VM_NAME" \
    podman compose -f /srv/project/.devenv/services-compose.yaml up -d
echo

# --- mode-specific: framework install ------------------------------------
if [[ $MODE == "bake" ]]; then
    "$HOME_DIR/scripts/install-moodle.sh"
    echo

    info "==> Patching config.php with phpunit settings"
    "$HOME_DIR/scripts/in-vm" "$VM_NAME" \
        sudo /srv/mosaic/scripts/configure-phpunit "/srv/$FRAMEWORK/config.php"
    echo

    if [[ $(project_plugin_count) -gt 0 ]]; then
        "$HOME_DIR/scripts/upgrade-moodle.sh"
        echo
    fi
elif [[ $MODE == "mount" ]]; then
    "$HOME_DIR/scripts/install-laravel.sh"
    echo
fi

# --- common: (re)start nginx + php-fpm -----------------------------------
# render-services.sh (above) just rewrote .devenv/nginx.conf, which
# nginx reads via the sites-enabled symlink. nginx is `enable`d in the
# Lima template, so it may already be running from render-lima.sh's
# post-provision VM cycle — bound against the PREVIOUS .devenv/nginx.conf
# (e.g. the stale port when rebuilding a re-ported/copied project).
# `systemctl start` is a no-op on an already-running unit and would
# strand nginx on the old port; `restart` forces it to re-read the
# freshly-rendered config and rebind.
info "==> Restarting nginx + php-fpm"
"$HOME_DIR/scripts/in-vm" "$VM_NAME" \
    sudo systemctl restart "php${PHP_VERSION}-fpm" nginx
echo

ok "Build complete"
echo
info "Open it:"
say  "  http://${WWWROOT}:${WEB_PORT}/"
if [[ $MODE == "bake" ]]; then
    say  "  admin / Password1!"
fi
echo
info "Next:"
say  "  mosaic status        # one-screen summary"
if [[ $MODE == "bake" ]]; then
    say  "  mosaic init-phpunit  # set up the phpunit test database"
fi
say  "  mosaic shell         # drop into the VM at /srv/project"
say  "  mosaic down          # stop services without losing state"
